# Numpy

NumPy (Numerical Python) is an open-source Python library used for numerical computing. It provides a powerful **N-dimensional array (ndarray)** object along with mathematical functions to perform fast and efficient operations on large datasets.

**Why Numpy over Python List**

- Faster than Python Lists
- Uses homogeneous data types
- Optimized for numerical computations
- Foundation for Pandas, Scikit-Learn, TensorFlow, etc.

`Vector` : One dimensional array  
`Matrix` : 2D array

### Importing Numpy

In [2]:
import numpy as np

### Creating a Numpy Array

**1. Using Python List**

- Python list can be converted into numpy array.  
    - `Syntax` - np.array(*python_list*)

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr)

numpy.ndarray

***2D array***

In [5]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

**2. Array Function**

**arange function**

- Creating a array within a range with evenly spaced values
    - `Syntax` - np.arange(*start, stop, step*)
- *stop* is exclusive
- By default: 
    - *start* - 0
    - *step* - 1
    - Only *stop* is mandatory    

In [6]:
a=np.arange(2,22,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
a1 = np.arange(15)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Array of zeros and ones**

- `Syntax`
    - np.zeros((*rows,columns*))  
    - np.ones((*rows,columns*))

In [8]:
b=np.zeros((3,3))
print(b)
o=np.ones((2,2))
o

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1.],
       [1., 1.]])

**Array of Identity Matrix**

- A identity matrix is returned of desired order
    - `Syntax` : np.identity( *matrx_order* )

In [9]:
i = np.identity(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**linspace function**

- Array of evenly spaced numbers over a specified interval
- np.linspace(*start, end, no_of_elements*)

In [10]:
p=np.linspace(1,50,10)
p

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

**3. Random Array Generation (using Random Library)**

| Function | Distribution | Range / Mean | Description |
|----------|--------------|--------------|-------------|
| `np.random.rand(shape)` | Uniform Distribution | `0 ≤ x < 1` | Generates random floating-point numbers uniformly between 0 and 1. |
| `np.random.randn(shape)` | Standard Normal Distribution | Mean = `0`, Std = `1` (typically values between `-3` and `3`) | Generates random numbers from a standard normal (Gaussian) distribution. |
| `np.random.randint(low, high, size)` | Uniform Integer Distribution | `low ≤ x < high` | Generates random integers within the specified range. |

In [11]:
np.random.rand(10)

array([0.45838925, 0.57333248, 0.8775513 , 0.73523956, 0.29243296,
       0.10751129, 0.70017019, 0.40996874, 0.25810543, 0.91047299])

In [12]:
np.random.randn(10)

array([ 0.74006627, -0.73346158, -0.29301767, -1.65991883,  0.03414929,
        0.45041653, -0.40306908,  0.29174261, -0.41255301,  0.6232296 ])

 Random Number within specific range
 - `Syntax` - .randint(*start, end, size*)

In [13]:
np.random.randint(10,20,4) 

array([13, 11, 12, 17], dtype=int32)

**3. Copying a array**

- Python function, creates a shallow copy of mutable collection.
- `Syntax` - *array_to_copy*.copy()

In [14]:
t = np.identity(5)
t

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
c = t.copy()
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])