# Numpy

NumPy (Numerical Python) is an open-source Python library used for numerical computing. It provides a powerful **N-dimensional array (ndarray)** object along with mathematical functions to perform fast and efficient operations on large datasets.

**Why Numpy over Python List**

- Faster than Python Lists
- Uses homogeneous data types
- Optimized for numerical computations
- Foundation for Pandas, Scikit-Learn, TensorFlow, etc.

`Vector` : One dimensional array  
`Matrix` : 2D array

### Importing Numpy

In [13]:
import numpy as np

### Creating a Numpy Array

**1. Using Python List**

- Python list can be converted into numpy array.  
    - `Syntax` - np.array(*python_list*)

In [14]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
type(arr)

numpy.ndarray

***2D array***

In [16]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

**2. Array Function**

**arange function**

- Creating a array within a range with evenly spaced values
    - `Syntax` - np.arange(*start, stop, step*)
- *stop* is exclusive
- By default: 
    - *start* - 0
    - *step* - 1
    - Only *stop* is mandatory    

In [17]:
a=np.arange(2,22,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [18]:
a1 = np.arange(15)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**Array of zeros and ones**

- `Syntax`
    - np.zeros((*rows,columns*))  
    - np.ones((*rows,columns*))

In [19]:
b=np.zeros((3,3))
print(b)
o=np.ones((2,2))
o

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1.],
       [1., 1.]])

**Array of Identity Matrix**

- A identity matrix is returned of desired order
    - `Syntax` : np.identity( *matrx_order* )

In [20]:
i = np.identity(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**linspace function**

- Array of evenly spaced numbers over a specified interval
- np.linspace(*start, end, no_of_elements*)

In [21]:
p=np.linspace(1,50,10)
p

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

**3. Random Array Generation (using Random Library)**

| Function | Distribution | Range / Mean | Description |
|----------|--------------|--------------|-------------|
| `np.random.rand(shape)` | Uniform Distribution | `0 ≤ x < 1` | Generates random floating-point numbers uniformly between 0 and 1. |
| `np.random.randn(shape)` | Standard Normal Distribution | Mean = `0`, Std = `1` (typically values between `-3` and `3`) | Generates random numbers from a standard normal (Gaussian) distribution. |
| `np.random.randint(low, high, size)` | Uniform Integer Distribution | `low ≤ x < high` | Generates random integers within the specified range. |

In [22]:
np.random.rand(10)

array([0.97558049, 0.75537851, 0.91303129, 0.09397731, 0.45284929,
       0.37696561, 0.08666833, 0.30557674, 0.04001865, 0.99051452])

In [23]:
np.random.randn(10)

array([ 1.60412197,  0.66085779,  1.73655299, -0.63007522, -0.12676631,
        1.92112778, -0.1925384 , -1.76802409,  1.25613649,  1.73284723])

 Random Number within specific range
 - `Syntax` - .randint(*start, end, size*)

In [24]:
np.random.randint(10,20,4) 

array([13, 18, 18, 17], dtype=int32)

**3. Copying a array**

- Python function, creates a shallow copy of mutable collection.
- `Syntax` - *array_to_copy*.copy()

In [25]:
t = np.identity(5)
t

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
c = t.copy()
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Array Attributes

In [46]:
arr1 = np.array([1,2,3,4,5])
arr1 # 1D array

array([1, 2, 3, 4, 5])

In [38]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 # 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
arr3 # 3D array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

**.shape**

- returns length of each dimension

In [47]:
arr1.shape

(5,)

In [28]:
arr2.shape

(3, 3)

In [43]:
np.shape(arr2)

(3, 3)

In [42]:
arr3.shape

(2, 2, 2)

**.ndim**

- returns number of dimension

In [45]:
arr3.ndim

3

In [48]:
arr1.ndim

1

**.size**

- returns number of elements

In [29]:
arr2.size

9

In [44]:
np.size(arr3)

8

**.itemsize**

- returns size of single array element in bytes

In [54]:
arr1.itemsize
# 8 since the element is of type int64

8

In [53]:
i.itemsize

8

**.dtype**

- returns datatype and single element size in bits

In [30]:
arr2.dtype

dtype('int64')

In [49]:
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
i.dtype

dtype('float64')

### Array Methods

| Method | Syntax | Description |
|--------|--------|-------------|
| Minimum | `array.min()` | Returns the smallest element. |
| Maximum | `array.max()` | Returns the largest element. |
| Sum | `array.sum()` or `np.sum(array)` | Returns the sum of all elements. |
| Sum (Axis-wise) | `np.sum(array, axis=0)` | Returns the column-wise sum. |
| Sum (Axis-wise) | `np.sum(array, axis=1)` | Returns the row-wise sum. |
| Mean | `array.mean()` | Returns the average of all elements. |
| Standard Deviation | `array.std()` | Returns the standard deviation. |
| Variance | `array.var()` | Returns the variance. |
| Index of Maximum | `array.argmax()` | Returns the index of the maximum element. |
| Index of Minimum | `array.argmin()` | Returns the index of the minimum element. |

In [31]:
print(arr2.min())
print(arr2.max())

1
9


In [32]:
arr2.sum()

np.int64(45)

In [33]:
print(np.sum(arr2,axis=1)) #Row wise
print(np.sum(arr2,axis=0)) #Column wise

[ 6 15 24]
[12 15 18]


In [34]:
print(arr2.mean())
print(arr2.std())

5.0
2.581988897471611


In [35]:
print(arr2.argmax())
print(arr2.argmin())

8
0


### Array Reshaping and Resizing

`Reshaping` - Converts a 1D matrix into nD matrix  
`Resize` - Storing the reshaped matrix in same variable

In [36]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

- .reshape( *rows, columns* )

In [37]:
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])