# Numpy

NumPy (Numerical Python) is an open-source Python library used for numerical computing. It provides a powerful **N-dimensional array (ndarray)** object along with mathematical functions to perform fast and efficient operations on large datasets.

**Why Numpy over Python List**

- Faster than Python Lists
- Uses homogeneous data types
- Optimized for numerical computations
- Foundation for Pandas, Scikit-Learn, TensorFlow, etc.

### Importing Numpy

In [24]:
import numpy as np

### Creating a Numpy Array

**1. Using Python List**

- Python list can be converted into numpy array.  
    - `Syntax` - np.array(*python_list*)

In [25]:
arr=np.array([1,2,3,4,5,6,7,8,9])

**2. Array Function**

**arange function**

- Creating a array within a range with evenly spaced values
    - `Syntax` - np.arange(*start, stop, step*)

In [26]:
a=np.arange(2,22,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

**Array of zeros and ones**

- `Syntax`
    - np.zeros((*rows,columns*))  
    - np.ones((*rows,columns*))

In [27]:
b=np.zeros((3,3))
print(b)
o=np.ones((2,2))
o

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1.],
       [1., 1.]])

**linspace function**

- Array of evenly spaced numbers over a specified interval
- np.linspace(*start, end, no_of_elements*)

In [28]:
p=np.linspace(1,50,10)
p

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

**3. Random Array Generation (using Random Library)**

| Function | Distribution | Range / Mean | Description |
|----------|--------------|--------------|-------------|
| `np.random.rand(shape)` | Uniform Distribution | `0 ≤ x < 1` | Generates random floating-point numbers uniformly between 0 and 1. |
| `np.random.randn(shape)` | Standard Normal Distribution | Mean = `0`, Std = `1` (typically values between `-3` and `3`) | Generates random numbers from a standard normal (Gaussian) distribution. |
| `np.random.randint(low, high, size)` | Uniform Integer Distribution | `low ≤ x < high` | Generates random integers within the specified range. |

In [29]:
np.random.rand(10)

array([0.14774545, 0.45959558, 0.64085065, 0.30140709, 0.55552551,
       0.09826942, 0.96024091, 0.67836836, 0.3355014 , 0.66767622])

In [30]:
np.random.randn(10)

array([ 0.17768776, -1.16064974,  0.31809841,  1.08143039, -0.25430513,
        1.6654376 ,  0.20780534, -0.56871882,  0.29857861, -0.43237758])

 Random Number within specific range
 - `Syntax` - .randint(*start, end, size*)

In [31]:
np.random.randint(10,20,4) 

array([19, 13, 11, 19], dtype=int32)

### Array Attributes

In [32]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**.shape**

- returns number of rows and columns

In [33]:
arr.shape

(3, 3)

**.size**

- returns number of elements

In [34]:
arr.size

9

**.dtype**

- returns datatype

In [35]:
arr.dtype

dtype('int64')

### Array Methods

| Method | Syntax | Description |
|--------|--------|-------------|
| Minimum | `array.min()` | Returns the smallest element. |
| Maximum | `array.max()` | Returns the largest element. |
| Sum | `array.sum()` or `np.sum(array)` | Returns the sum of all elements. |
| Sum (Axis-wise) | `np.sum(array, axis=0)` | Returns the column-wise sum. |
| Sum (Axis-wise) | `np.sum(array, axis=1)` | Returns the row-wise sum. |
| Mean | `array.mean()` | Returns the average of all elements. |
| Standard Deviation | `array.std()` | Returns the standard deviation. |
| Variance | `array.var()` | Returns the variance. |
| Index of Maximum | `array.argmax()` | Returns the index of the maximum element. |
| Index of Minimum | `array.argmin()` | Returns the index of the minimum element. |

In [36]:
print(arr.min())
print(arr.max())

1
9


In [37]:
arr.sum()

np.int64(45)

In [38]:
print(np.sum(arr,axis=1)) #Row wise
print(np.sum(arr,axis=0)) #Column wise

[ 6 15 24]
[12 15 18]


In [39]:
print(arr.mean())
print(arr.std())

5.0
2.581988897471611


In [40]:
print(arr.argmax())
print(arr.argmin())

8
0


### Array Reshaping and Resizing

`Reshaping` - Converts a 1D matrix into nD matrix  
`Resize` - Storing the reshaped matrix in same variable

In [41]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

- .reshape( *rows, columns* )

In [42]:
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])