In [37]:
import numpy as np

# Indexing and Slicing of Vectors

In [38]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### Indexing

- Indexing works just like lists (starts from 0)

In [39]:
arr[2]

np.int64(13)

### Slicing

`Syntax` - *array*[*start : end* ]  
- start - include, end - exclude
-  if starting value is not given the default is 0 and if end is not given array is sliced till last element
- whole array is returend if both start and end index are not given

In [40]:
arr[:3]

array([11, 12, 13])

In [41]:
arr[:] # whole array is returned

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

**Steps is Slicing**

-  `Syntax` - *array*[ *start :: steps* ] 

In [42]:
arr[3::2]

array([14, 16, 18, 20])

### Indexing and Slicing of Matrix

In [43]:
a=np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

**Indexing**

- `Syntax` - *array*[*rows , columns*]

In [44]:
a[5,2]

np.int64(28)

**Slicing**

- The sliced portion is returend in vector if only one dimension is given


In [45]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

- If only one index is given then that will target rows


In [46]:
a[1]

array([ 6,  7,  8,  9, 10])

- For a portion, slice rows as well as columns

In [47]:
a[:2,2:4]

array([[3, 4],
       [8, 9]])

In [48]:
a[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

* Slicing a column:  
    * `Syntax` - *array*[*row , column*]

In [53]:
# Returns anly column in vector form
a[:,2]

array([ 3,  8, 13, 18, 23, 28])

### Boolean Indexing

- Uses boolean mask i.e. True and False, to filter and extract specific elements(True) from a array
- Returns the boolean output of every index creating a new list.
- Only the True value can be extracted.

In [50]:
ar=np.arange(11,21)
ar

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [51]:
# List of boolean outputs
bool_index=ar%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [52]:
#Extracts only the True output indices.
ar=ar[bool_index]
ar

array([12, 14, 16, 18, 20])