In [3]:
import numpy as np

# Array Attributes

In [4]:
arr1 = np.array([1,2,3,4,5])
arr1 # 1D array

array([1, 2, 3, 4, 5])

In [5]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 # 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
arr3 # 3D array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
i = np.identity(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Attributes

| Attribute | Syntax | Equivalent Function/Method | Description |
|---|---|---|---|
| **Shape** | `array.shape` | `np.shape(array)` | Returns the length of each dimension. |
| **No. of Dimensions** | `array.ndim` | — | Returns the number of dimensions. |
| **Size** | `array.size` | `np.size(array)` | Returns the total number of elements. |
| **Item Size** | `array.itemsize` | — | Returns the size of a single array element in bytes. |
| **Data Type** | `array.dtype` | — | Returns the data type of the array elements. |

In [7]:
arr1.shape

(5,)

In [8]:
np.shape(arr3)

(2, 2, 2)

In [9]:
arr1.ndim

1

In [10]:
arr3.ndim

3

In [11]:
arr2.size

9

In [12]:
arr1.itemsize

8

In [13]:
arr2.dtype

dtype('int64')

In [16]:
i.dtype

dtype('float64')

### Array Methods

| Method | Syntax | Description |
|--------|--------|-------------|
| Minimum | `array.min()` | Returns the smallest element. |
| Maximum | `array.max()` | Returns the largest element. |
| Sum | `array.sum()` or `np.sum(array)` | Returns the sum of all elements. |
| Mean | `array.mean()` | Returns the average of all elements. |
| Standard Deviation | `array.std()` | Returns the standard deviation. |
| Variance | `array.var()` | Returns the variance. |
| Index of Maximum | `array.argmax()` | Returns the index of the maximum element. |
| Index of Minimum | `array.argmin()` | Returns the index of the minimum element. |

`axis = 0` - Column-wise operation  
`axis = 1` - Row-wise operation

In [17]:
print(arr2.min())
print(arr2.max()) 

1
9


In [18]:
arr2.sum()

np.int64(45)

In [19]:
print(np.sum(arr2,axis=1)) #Row wise
print(np.sum(arr2,axis=0)) #Column wise

[ 6 15 24]
[12 15 18]


In [20]:
print(arr2.mean())
print(arr2.std())

5.0
2.581988897471611


In [21]:
print(arr2.argmax())
print(arr2.argmin())

8
0
