In [1]:
import numpy as np

### Indexing and Slicing of Vectors

In [2]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

### Indexing

- Indexing works just like lists (starts from 0)

In [3]:
arr[2]

np.int64(13)

### Slicing

`Syntax` - *array*[*start : end* : *step*]  
- *start* - include, *end* - exclude
- *step* - increment value between elements
-  By default:
    - *start* : 0
    - *end* : end of list
    - *step* - 1
- whole array is returend if both start and end index are not given

In [4]:
arr[:3]

array([11, 12, 13])

In [5]:
arr[:] # whole array is returned

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[1:5:2]

array([12, 14])

In [7]:
arr[3::2]

array([14, 16, 18, 20])

### Indexing and Slicing of Matrix

In [8]:
a=np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

**Indexing**

- `Syntax` - *array*[*rows , columns*]

In [9]:
a[5,2]

np.int64(28)

**Slicing**

`Syntax` - *array*[*row , column*]

- The sliced portion is returend in vector if only one dimension is given


In [10]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

- Sliicing only rows
    - If only one index is given then that will target rows

In [11]:
a[1]

array([ 6,  7,  8,  9, 10])

- For a portion, slice rows as well as columns

In [12]:
a[:2,2:4]

array([[3, 4],
       [8, 9]])

In [13]:
a[4:,3:]

array([[24, 25],
       [29, 30]])

In [14]:
a[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [15]:
a[:3:2,3:]
# 1st row and third row, 4th and 5th column

array([[ 4,  5],
       [14, 15]])

* Slicing a column:  
    - Returns anly column in vector form

In [16]:
a[:,2]

array([ 3,  8, 13, 18, 23, 28])

### Advanced Indexing (Fancy Indexing)

- Numpy technique used to select multiple specific elements from an array by passing an array/list of indices

In [31]:
n = np.arange(10,20)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [33]:
n[[1,5,8]] #Gives elements of desired index

array([11, 15, 18])

In [25]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [34]:
a[[1,2,3]] #For 2D matrix

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

For element indexing in 2D matrix

In [35]:
a[[1,3], [4,2]]

array([10, 18])

### Boolean Indexing

- Uses boolean mask i.e. True and False, to filter and extract specific elements(True) from a array
- Returns the boolean output of every index creating a new list.
- Only the True value can be extracted.

In [17]:
ar=np.arange(11,21)
ar

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
# List of boolean outputs
bool_index=ar%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [19]:
#Extracts only the True output indices.
ar=ar[bool_index]
ar

array([12, 14, 16, 18, 20])

## Iterating over Array

- Iteratiing over vectors; works with general for loop
- Does not work with matrix, as for loop returns each row
- For iterating over n-d array, `np.iter` is used
- Nested loop is also a solution but not effecient

In [20]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [21]:
for i in arr:
    print(i)

11
12
13
14
15
16
17
18
19
20


In [22]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [23]:
for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30


This gives all the elements like vector

In [24]:
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
