In [2]:
import numpy as np

# Array Operations

### Arithmetic Operations

- Performs element-wise operations on corresponding elements.
- Arrays must have the same shape or be broadcastable.
- There are equivalent fucntions used instead of symbols.

| Operation | Operator | Equivalent NumPy Function |
|-----------|:--------:|---------------------------|
| Addition | `+` | `np.add(a, b)` |
| Subtraction | `-` | `np.subtract(a, b)` |
| Multiplication | `*` | `np.multiply(a, b)` |
| Division | `/` | `np.divide(a, b)` |
| Floor Division | `//` | `np.floor_divide(a, b)` |
| Modulus / Remainder | `%` | `np.mod(a, b)` |
| Exponentiation | `**` | `np.power(a, b)` |

In [3]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

Sum

In [4]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [5]:
np.add(a1,a2)

array([ 7,  9, 11, 13, 15])

Difference

In [6]:
a1 - a2

array([-5, -5, -5, -5, -5])

Product

In [7]:
np.multiply(a1,a2)

array([ 6, 14, 24, 36, 50])

Division

In [8]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [9]:
np.divide(a1,a2)

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

Floor Division

In [10]:
a1 // a2

array([0, 0, 0, 0, 0])

Power

In [11]:
np.power(a1,a2)

array([      1,     128,    6561,  262144, 9765625])

### Broadcasting

Broadcasting is NumPy's ability to perform arithmetic operations on arrays of different shapes without explicitly copying data.  
It automatically expands the smaller array to match the shape of the larger array.
 
**Benefits**
- Eliminates the need for loops
- Faster and memory efficient
- Simplifies mathematical operations on arrays

**Broadcasting Rules**
1. If the dimensions are different, NumPy adds `1` to the left of the smaller array's shape.
2. Two dimensions are compatible if:
   - They are equal, **or**
   - One of them is `1`.
3. If the dimensions are not compatible, NumPy raises a **ValueError**.

In [12]:
l=[1,2,3,4,5]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5])

In [13]:
arr+10

array([11, 12, 13, 14, 15])

In [14]:
arr2=np.arange(1,16).reshape(5,3)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [15]:
arr2+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22],
       [23, 24, 25]])

In [16]:
l=[10,20,30,40]
arr=np.array(l)
arr

array([10, 20, 30, 40])

In [17]:
arr + 10

array([20, 30, 40, 50])

In [18]:
arr2=np.arange(1,21).reshape(4,5)

In [19]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
arr2=arr2*10

In [21]:
arr2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

### Deep and Shallow Copy

**Shallow Copy**
- Shares the same memory as the original array.
- Changes made to one array are reflected in the other.

**Deep Copy**
- Creates a completely independent copy.
- Changes made to the copied array do not affect the original array.

In [22]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [24]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
a[4:6] *10 

array([50, 60])

In [26]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
b = a.copy() #Shallow Copy
# b=a     #Deep Copy
b[0] = 99 

In [28]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Matrix Operation 

| Operation | Operator | Equivalent NumPy Function/ Method |
|-----------|:--------:|---------------------------|
| Element-wise Multiplication (Broadcasting) | `*` | `np.multiply(a,b)` |
| Matrix Multiplication | `@` | `np.dot(a,b)` / `np.matmul(a,b)` |
| Transpose | `.T` | `np.transpose(a)` / `array.transpose()` |

In [30]:
m=np.array([[1,2],[4,5]])
n=np.array([[7,8],[3,6]])
m

array([[1, 2],
       [4, 5]])

In [31]:
n

array([[7, 8],
       [3, 6]])

In [32]:
m * n #Broadcasting

array([[ 7, 16],
       [12, 30]])

In [33]:
m @ n #Matrix Multiplication

array([[13, 20],
       [43, 62]])

In [34]:
m.dot(n)

array([[13, 20],
       [43, 62]])