In [1]:
import numpy as np

## Array Reshaping and Resizing

| Method | Method/ Attribute | Equivalent Function | Description |
|---|---|---|---|
| **Reshape** | `array.reshape(shape)` | `np.reshape(array, shape)` | Changes the shape of an array without changing its data. |
| **Resize** | `array.resize(shape)` | `np.resize(array, shape)` | Changes the size/shape of an array and stores the result in the same array. |
| **Ravel** | `array.ravel()` | `np.ravel(array)` | Converts a multidimensional array into a 1D array. |
| **Transpose** | `array.transpose()` / `array.T` | `np.transpose(array)` | Transposes an array by swapping its rows and columns (axes). |

In [2]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [3]:
arr = arr.reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [4]:
resize = np.resize(arr,(6,6))
resize

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [ 1,  2,  3,  4,  5,  6]])

In [5]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [6]:
np.transpose(arr)

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

In [7]:
arr.T

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

In [8]:
arr.transpose()

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

## Stacking and Splitting Arrays

**Stacking Arrays**

- Combines two or more arrays into a single array.
- Arrays must have compatible dimensions.
- The stacked vectors are stacked in the form of matrix or vectors vertically (row wise) or horizontally (column wise)*  

| Function | Direction | Description |
|----------|-----------|-------------|
| `np.vstack((Matrix1, Matrix2))` | Vertical (Row-wise) | Stacks arrays vertically by adding rows. The resulting array has more rows while the number of columns remains the same. |
| `np.hstack((Matrix1, Matrix2))` | Horizontal (Column-wise) | Stacks arrays horizontally by adding columns. For 1D arrays, the result is a longer 1D array. |
| `np.column_stack((Matrix1, Matrix2))` | Horizontal (Column-wise) | Stacks 1D arrays as columns to create a 2D matrix. For 2D arrays, it behaves similarly to `np.hstack()`. |
| `np.stack((Matrix1, Matrix2), axis = )` | Specified by `axis` | Joins arrays along a new axis. The `axis` parameter determines the direction in which the arrays are stacked. |

- For 2D( and higher dimensional) arrays the result for column_stack and hstack are same

In [9]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.arange(6).reshape(2,3)
d = np.arange(10,16).reshape(2,3)
a

array([1, 2, 3, 4])

In [10]:
b

array([5, 6, 7, 8])

In [11]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
d

array([[10, 11, 12],
       [13, 14, 15]])

In [13]:
np.hstack((a,b)) #A longer array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.hstack((c,d)) 

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [15]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
np.vstack((c,d))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [17]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [18]:
np.column_stack((c,d))

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [19]:
np.stack((a,b),axis = 1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [20]:
np.stack((c,d),axis = 0)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [21]:
np.stack((c,d),axis=1)

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[ 3,  4,  5],
        [13, 14, 15]]])

**Splitting Arrays**

- Splits an array into multiple sub-arrays.
- Returns a list of sub-arrays.
- Original array remains unchanged.

| Function | Direction | Description |
|----------|-----------|-------------|
| `np.split(array, sections, axis = ` | General | Splits an array into equal sub-arrays or at specified indices. |
| `np.vsplit(array, sections)` | Vertical (Row-wise) | Splits an array into multiple arrays along the rows. |
| `np.hsplit(array, sections)` | Horizontal (Column-wise) | Splits an array into multiple arrays along the columns. |

- `sections` - should be in such that the sub-arrays are evenly seperated
    - vsplit - any factor of row
    - hsplit - any factor of column
    - i.e. must be factor of dimension you're splitting

In [22]:
ar = np.arange(0,20).reshape(10,2)
ar

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

- For a array of 10 x 2 dimension: 
    - vsplit - section - 1,2,5,10
    - hsplit - section - 1 ,2

In [23]:
np.split(ar, 10, axis = 0)

[array([[0, 1]]),
 array([[2, 3]]),
 array([[4, 5]]),
 array([[6, 7]]),
 array([[8, 9]]),
 array([[10, 11]]),
 array([[12, 13]]),
 array([[14, 15]]),
 array([[16, 17]]),
 array([[18, 19]])]

In [24]:
np.vsplit(ar,5) #Row-wise

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[ 8,  9],
        [10, 11]]),
 array([[12, 13],
        [14, 15]]),
 array([[16, 17],
        [18, 19]])]

In [25]:
np.hsplit(ar, 2) #Column wise

[array([[ 0],
        [ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12],
        [14],
        [16],
        [18]]),
 array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]])]

In [26]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [27]:
np.hsplit(arr, 2)

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21],
        [25, 26, 27]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24],
        [28, 29, 30]])]

In [28]:
np.hsplit(arr, 3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30]])]