In [65]:
import numpy as np

**Indexing and Slicing of Vectors**

In [66]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Indexing

In [67]:
#Indexing works just like lists (starts from 0)
arr[2]

np.int64(13)

Slicing

In [68]:
#name[start:end] (start - include, end - exclude)
arr[:3] #if startign value is not given the default is 0 and if end is not given array is sliced till last element

array([11, 12, 13])

In [69]:
arr[:] #whole array is returend if not start or end index are given

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Steps is Slicing

In [70]:
#name[start::steps]
arr[3::2]


array([14, 16, 18, 20])

**Indexing and Slicing of Matrix**

In [71]:
a=np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Indexing

In [72]:
# name[row,column]
a[5,2]

np.int64(28)

Slicing

In [73]:
#THe sliced portion is returend in vector if only one dimension is given
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [74]:
#If only one index is given then that will target rows
a[1]

array([ 6,  7,  8,  9, 10])

In [75]:
#For a portion, slice rows as well as columns
a[:2,2:4]

array([[3, 4],
       [8, 9]])

In [76]:
a[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [77]:
# Slicing a entire column
a[:,2]

array([ 3,  8, 13, 18, 23, 28])

****Boolean Indexing****

Uses boolean mask i.e. True and False, to filter and extract specific elements(True) from a array


In [78]:
ar=np.arange(11,21)
ar

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [79]:
#Returns the boolean output of every index of ar creating a new list
bool_index=ar%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [80]:
#Extracts only the True output indices.
ar=ar[bool_index]
ar

array([12, 14, 16, 18, 20])