In [46]:
import numpy as np

# Array Operations

### Arithmetic Operations

- Performs Operations on corresponding elements of array 
- Size of arrays must be same
- There are equivalent fucntions used instead of symbols.

| Operation | Operator | Equivalent NumPy Function |
|-----------|:--------:|---------------------------|
| Addition | `+` | `np.add(a, b)` |
| Subtraction | `-` | `np.subtract(a, b)` |
| Multiplication | `*` | `np.multiply(a, b)` |
| Division | `/` | `np.divide(a, b)` |
| Floor Division | `//` | `np.floor_divide(a, b)` |
| Modulus / Remainder | `%` | `np.mod(a, b)` |
| Exponentiation | `**` | `np.power(a, b)` |

In [47]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

Sum

In [48]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [49]:
np.add(a1,a2)

array([ 7,  9, 11, 13, 15])

Difference

In [50]:
a1 - a2

array([-5, -5, -5, -5, -5])

Product

In [51]:
np.multiply(a1,a2)

array([ 6, 14, 24, 36, 50])

Division

In [52]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [53]:
np.divide(a1,a2)

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

Floor Division

In [54]:
a1 // a2

array([0, 0, 0, 0, 0])

Power

In [55]:
np.power(a1,a2)

array([      1,     128,    6561,  262144, 9765625])

### Broadcasting

Broadcasting is NumPy's ability to perform arithmetic operations on arrays of different shapes without explicitly copying data.  
It automatically expands the smaller array to match the shape of the larger array.
 
**Benefits**
- Eliminates the need for loops
- Faster and memory efficient
- Simplifies mathematical operations on arrays

**Broadcasting Rules**
1. If the dimensions are different, NumPy adds `1` to the left of the smaller array's shape.
2. Two dimensions are compatible if:
   - They are equal, **or**
   - One of them is `1`.
3. If the dimensions are not compatible, NumPy raises a **ValueError**.

In [56]:
l=[1,2,3,4,5]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5])

In [57]:
arr+10

array([11, 12, 13, 14, 15])

In [58]:
arr2=np.arange(1,16).reshape(5,3)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [59]:
arr2+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22],
       [23, 24, 25]])

In [60]:
l=[10,20,30,40]
arr=np.array(l)
arr

array([10, 20, 30, 40])

In [61]:
arr + 10

array([20, 30, 40, 50])

In [62]:
arr2=np.arange(1,21).reshape(4,5)

In [63]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [64]:
arr2=arr2*10

In [65]:
arr2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

### Deep and Shallow Copy

**Shallow Copy**
- Shares the same memory as the original array.
- Changes made to one array are reflected in the other.

**Deep Copy**
- Creates a completely independent copy.
- Changes made to the copied array do not affect the original array.

In [66]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [67]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [68]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [69]:
a[4:6] *10 

array([50, 60])

In [70]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [71]:
b = a.copy() #Shallow Copy
# b=a     #Deep Copy
b[0] = 99 

In [72]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [73]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Matrix Operation 

- `*` performs element-wise multiplication (supports broadcasting).
- `@` or `np.dot()` performs actual matrix multiplication.

In [74]:
m=np.array([[1,2],[4,5]])
n=np.array([[7,8],[3,6]])

In [75]:
print("m:",m,"\nn:",n)

m: [[1 2]
 [4 5]] 
n: [[7 8]
 [3 6]]


In [76]:
m * n #Broadcasting

array([[ 7, 16],
       [12, 30]])

In [77]:
m @ n #Matrix Multiplication

array([[13, 20],
       [43, 62]])

**Transpose**

- *Rows and columns are replaced*  
- *matrix*.T

In [78]:
m.T

array([[1, 4],
       [2, 5]])

### Advanced Array Manipulation

**Stacking Array**  
- Can't stack 2 matrix  but can stack or merge 2 vectors. 
- The stacked vectors are stacked in the form of matrix or vectors vertically (row wise) or horizontally (column wise)*  

| Function | Direction | Description |
|----------|-----------|-------------|
| `np.vstack((Matrix1, Matrix2))` | Vertical (Row-wise) | Stacks arrays vertically by adding rows. The resulting array has more rows while the number of columns remains the same. |
| `np.hstack((Matrix1, Matrix2))` | Horizontal (Column-wise) | Stacks arrays horizontally by adding columns. For 1D arrays, the result is a longer 1D array. |
| `np.column_stack((Matrix1, Matrix2))` | Horizontal (Column-wise) | Stacks 1D arrays as columns to create a 2D matrix. For 2D arrays, it behaves similarly to `np.hstack()`. |

In [79]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [80]:
np.vstack((a,b)) #Vertically

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
np.hstack((a,b)) #Horizontally

array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

**Splitting Arrays**

- *Matrix can be split in to number of parts*  


| Function | Direction | Description |
|----------|-----------|-------------|
| `np.split(array, sections)` | General | Splits an array into equal sub-arrays or at specified indices. |
| `np.vsplit(array, sections)` | Vertical (Row-wise) | Splits an array into multiple arrays along the rows. |
| `np.hsplit(array, sections)` | Horizontal (Column-wise) | Splits an array into multiple arrays along the columns. |

In [83]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
np.split(c,4) #General

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [85]:
np.hsplit(c,4)  #Col_wise

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [86]:
np.vsplit(c,4) #Row_wise

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [87]:
for i in c:
    print(i)  #As the array is already split 

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
