In [78]:
import numpy as np

****Array Operations****

**Arithmetic Operations**

Performs Operations on corresponding elements of array 
Size of arrays must be same

In [79]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [80]:
#Sum
a1 + a2

array([ 7,  9, 11, 13, 15])

In [81]:
#Difference
a1 - a2

array([-5, -5, -5, -5, -5])

In [82]:
#Product
a1 * a2

array([ 6, 14, 24, 36, 50])

In [83]:
#Division
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [84]:
#Floor Division
a1 // a2

array([0, 0, 0, 0, 0])

In [85]:
#Power
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

**Broadcasting**

In [86]:
l=[1,2,3,4,5]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5])

In [87]:
arr+10

array([11, 12, 13, 14, 15])

In [88]:
arr2=np.arange(1,16).reshape(5,3)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [89]:
arr2+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22],
       [23, 24, 25]])

Broadcasting

In [90]:
l=[10,20,30,40]
arr=np.array(l)
arr

array([10, 20, 30, 40])

In [91]:
arr + 10

array([20, 30, 40, 50])

In [92]:
arr2=np.arange(1,21).reshape(4,5)

In [93]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [94]:
arr2=arr2*10

In [95]:
arr2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200]])

**Deep and Shallow Copy**  
*Shallow Copy: When a arry is sliced  and performed operations in it sliced copy, no changes will occur in the original array as both are in seperate location in RAM*  
*Deep Copy: When a array is sliced and performed operations in it, the original array also changes as both variables are in the same location of RAM*

In [96]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [97]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [98]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [99]:
a[4:6] *10 

array([50, 60])

In [100]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [101]:
b = a.copy() #Shallow Copy
# b=a     #Deep Copy
b[0] = 99 

In [102]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [103]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Matrix Operation**  

**Matrix Multiplication**  
*In Matrix, * is used for multiplication with boradcasting. But for actual matrix multiplication @ is used.*  
*Matrix1* @ *Matrix2*     *OR* np.dot(*Matrix1,Matrix2*) 

In [104]:
m=np.array([[1,2],[4,5]])
n=np.array([[7,8],[3,6]])

In [105]:
print("m:",m,"\nn:",n)

m: [[1 2]
 [4 5]] 
n: [[7 8]
 [3 6]]


In [106]:
m * n #Broadcasting

array([[ 7, 16],
       [12, 30]])

In [107]:
m @ n #Matrix Multiplication

array([[13, 20],
       [43, 62]])

**Transpose**  
*Rows and columns are replaced*  
*Matrix*.T

In [108]:
m.T

array([[1, 4],
       [2, 5]])

**Advanced Array Manipulation**

Stacking Array  
*Can't stack 2 matrix  but can stack or merge 2 vectors. The stacked vectors are stacked in the form of matrix or vectors vertically (row wise) or horizontally (column wise)*  
np.vstack((*Matrix1, Matrix2*)) [Vertically]  *The stacked vectors are stored in the form of matrix vertically (row wise)*  
np.hstack((*Matrix1, Matrix2*))  [Horizontally] *The stacked arrays are stored in vector form merged Horizontally (column wise)*  
np.column_stack((*Matrix1, Matrix2*)) [Horizontally] *The stacked arrays are stored in matrix forms Horizontally(Column wise)*

In [109]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [110]:
np.vstack((a,b)) #Vertically

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [111]:
np.hstack((a,b)) #Horizontally

array([1, 2, 3, 4, 5, 6, 7, 8])

In [112]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Arrays  
*Matrix can be split in to number of parts*  
np.split(*Matrix*, **) and np.vsplit() ; splits the array row wise  
np.hsplit() ; splits the array column wise

In [113]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [114]:
np.split(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [115]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [120]:
np.vsplit(c,4) 

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
for i in c:
    print(i)  #As the array is already split 

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
