**Importing Numpy**

In [1]:
import numpy as np

Creating a Numpy Array

In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9])

**Array Function**

In [3]:
#1. Creating a array within a range with evenly spaced values
a=np.arange(2,22,2) #(start,stop,step)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
#2. array of zeros (rows,columns)
b=np.zeros((3,3))
print(b)
#3. array of ones(rows,columns)
o=np.ones((2,2))
o

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1.],
       [1., 1.]])

In [5]:
#4. Array of evenly spaced numbers over a specified interval
p=np.linspace(1,50,10) # (start,end,number_of_elements)
p

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

**Random Array Generation (using Random Library)**

In [6]:
#1. Random Array
#   Normalization (0 - 1)
np.random.rand(10)

array([0.56009253, 0.54987193, 0.43820506, 0.7123953 , 0.27081253,
       0.72153222, 0.83924813, 0.26786937, 0.05722516, 0.56184321])

In [7]:
#   Standardization (-3 - 3)
np.random.randn(10)

array([ 0.22763493, -1.64693684,  0.61777204, -0.72865247,  1.82684439,
       -0.3710068 , -0.36307891,  0.13328736, -0.41284326, -0.20607527])

In [8]:
#2. Random numbers within specific range   
np.random.randint(10,20,4) #(start,end,size)

array([17, 12, 12, 16], dtype=int32)

**Array Attributes**

In [9]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
#1. Returns number of rows and columns of array
arr.shape

(3, 3)

In [11]:
#2. Returns number of elements
arr.size

9

In [12]:
#3. Returns datatype
arr.dtype

dtype('int64')

**Array Methods**

In [13]:
#Minimum, Maximum, Sum(gives the sum of all the elements)
print(arr.min())
print(arr.max())
print(arr.sum())

1
9
45


In [14]:
#For Row or Columns wise sum: np.sum(array_name,axis = _) [axis =1 for row sie and 0 for column wise]
print(np.sum(arr,axis=1)) #Row wise
print(np.sum(arr,axis=0)) #Column wise

[ 6 15 24]
[12 15 18]


In [15]:
#Mean
print(arr.mean())
#Stadndard Deviation
print(arr.std())


5.0
2.581988897471611


In [16]:
#Arg
print(arr.argmax()) #Index of highest value element
print(arr.argmin()) #Index of lowest value element

8
0


**Array Reshaping and Resizing**

In [17]:
#Reshaping : Converts a 1D matrix into nD matrix
#Resize: Storing the reshaped matrix in same variable
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [18]:
arr=arr.reshape(6,5) #(rows,columns)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])